version: "2"

services:
 db:
  container_name: db_mysql
  image: mysql:5.7
  restart: always
  ports:
   - "9906:3306"
  environment:
   MYSQL_ROOT_PASSWORD: root
   MYSQL_DATABASE: eat
   MYSQL_USER: somedude
   MYSQL_PASSWORD: somedude
 react_server:
  build: ./
  container_name: react_server
  depends_on:
   - db
  ports:
   - "8080:8080"
  volumes: 
   - /./app/:/usr/src/app/
  stdin_open: true
  tty: true
